# Generated by Django 5.1 on 2024-12-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='following',
            new_name='followed_users',
        ),
    ]
