# Generated by Django 5.1 on 2024-12-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialite', '0002_rename_following_userprofile_followed_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='followed_users',
            new_name='following',
        ),
    ]
